#!/bin/bash
read num1
read num2
if [ $num1 \= $num2 ];
then 
  echo "X is equal to Y"
else
  if [ $num1 \> $num2 ];
  then
    echo "X is greater than Y";
  else
    echo "X is less than Y";
  fi;
fi;

# so basically this is structure is to memorize? Not same as with number arythmetic...
