#!/bin/bash

#if statements in Bash are often used in four important ways:

#1. if...then...fi statements
#2. if...then...else...fi statements  
#3. if..elif..else..fi  
#4. if..then..else..if..then..fi..fi.. (Nested Conditionals)

read input
if [ "$input" = "Y" ] 
then
  echo "Yes"
elif [ "$input" = "y" ]
then
  echo "Yes"
elif [ "$input" = "N" ]
then
  echo "No"
elif [ "$input" = "n" ]
then
  echo "No"
fi
