#!/bin/bash
read a
read b
read c
if [ "$a" = "$b" ];
then
  if [ "$b" = "$c" ];
  then
    echo "EQUILATERAL"
  else
    echo "ISOSCELES"
  fi
elif [ "$b" = "$c" ];
then
    echo "ISOSCELES"
else
    echo "SCALENE"
fi
